### PR TITLE
Run npm audit to fix some possible vulnerabilities

### PR DESCRIPTION
**Pull request by PatrickFfm93**
I did a test "npm run dev" afterwards and everything seems to work fine.
Just normal audit fix (without force) to not introduce breaking changes.

### CODE REVIEW

**Comment by PatrickFfm93** [comment]
Hello @kixelated , I would be very happy to contribute to this project. Therefore I wanted to provide a first simple commit/PR. I am very enthusiastic about MoQ and will soon be writing my master's thesis in this area alongside my job and would therefore like to participate in the projects.

**Review by kixelated — APPROVED** [review]
Oh sorry, I missed the first email for the PR.

**Comment by PatrickFfm93** [comment]
Hello @kixelated, due to this is my first PR here, do you want me to do something or just forgot to merge?

**Comment by kixelated** [comment]
> Hello @kixelated, due to this is my first PR here, do you want me to do something or just forgot to merge?

yes 🥇

**Pull request merged**
